- hosts: all
  tasks:
  - name: install packages 
    yum:
      name:  http
      state: latest
    register: hello
    ignore_errors: yes 

  - name: Restart apache
    service:
      name: httpd
      state: started 
    register: kaizen

  - debug: msg={{ hello }}
  - debug: msg={{ kaizen }}